/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  10143: {
    Canvas: {
      address: "0x3c2349772CEb7c1D2a9333A1Dabee13d2F236f63",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "pixelId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "color",
              type: "uint8",
            },
          ],
          name: "PixelUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "pixelId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "blockNumber",
              type: "uint256",
            },
          ],
          name: "StateCollision",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "canvas",
          outputs: [
            {
              internalType: "uint8",
              name: "color",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "lastUpdateBlock",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_x",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_y",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "_color",
              type: "uint8",
            },
          ],
          name: "drawPixel",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 14430716,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
