/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  10143: {
    Canvas: {
      address: "0x25f068644ef83Daf0d46e9C6a9e0cD12516639c6",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "pixelId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "painter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "color",
              type: "uint8",
            },
          ],
          name: "PixelUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "pixelId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "painter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "blockNumber",
              type: "uint256",
            },
          ],
          name: "StateCollision",
          type: "event",
        },
        {
          inputs: [],
          name: "GRID_SIZE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "canvas",
          outputs: [
            {
              internalType: "uint8",
              name: "color",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "lastUpdateBlock",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_x",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_y",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "_color",
              type: "uint8",
            },
          ],
          name: "drawPixel",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 14451336,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
